apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgCSiC9a1bgq8Ev0i+vYuyUfZ7y6uuXKXmUnN7ezWSKULLfj/BJdz8BuJyvfVJQ6yMQQnW7n6VL0H4Irkxzciy1GK9LeltyZPXliW4stVC5T5NMlwcolrLm7T9m/O39drbQMIxtZuGkak2uvM3cR9KLeV9/L1dgAQYpUz9Ks0gTIAGSLLpvGKtKGyNyv+K5Xtp7yuU4QYpZqlUS2UpCoXDdAs+05tSZDEG65Gqc8YB4aKx+oyON08gamswfB/SG1/REd18+vgTTwoGQiQfDlmBX4zH2Tg8ENhScOEOtpQUDzTuIifHfzioGvfDvUTJeWfKtuF3ob86WExC+D8BAQpoWDCqxlueIy0WgqezM4rAtQHdADYgIQjbkbbdvETF/POtwl8uAJTN4zo3q3KEo3T/NqqjQUFYYq5bdGHzsy0xqMqEsUr1tMHBlO97Tjd+/+NnNXjLbl8/gQnybtLaXN8IvjQUCJN29BS0gSTmlNfi1J3YSYAn5Tur+CEClDzFkliftO2RxeB43rKeOZ8SOUEEeg1ecil8sF7PtI3F8fwzOe4AcKiQgH9/TpOEMwfe1h9d1M1g0Z5xtsIqPYInBfcim+JXt5OK71F+qpOB5WSIksoW5TT+eLYIM8Y0NE/VPori+C9aRvDy/5FVhMsNwhhm/yO5msaMFc26Roi7e4nVSA/Hdi6CsdFmjqICHSUMwUQdR0z/0P64tXEcQb0C5/YcJcitEDSoXe39O8dTQpv9r26bIgFqiE/2INa4RVPfkvpcrW
