apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: common-secret
  namespace: ticketing
spec:
  encryptedData:
    JWT_SECRET: AgChq4iG3mg/GNecWr9NzSoQkoYhv5E+OiM4gYXWqGlYGOefEl28wozXmHrKiBzfLo1O+0tOT2CJiC5L9Ys2kCbgQXxi2bKC7tVD8IOaI+dpV4WUTRr/UW8qT5eQtOdy/ScWFF533z2El+P7gClIaEfgVmOikWR72nSCkidcll5UgGuSJUcdtS8d4jA7wfxCQWrczHSn+u5jLKw+5+3QSXCvA/L5FvD5Ky6sQrLoBTNbtxnyl5GRvWXBVJb/tO/9f5aCII5PIvlEAapGnBGGPY8mzuu9gOWZmWhVs4MVTrAbh73lEpvavkCbqtnIn/DGi1nFilN440FnZqXO+xTd0hbnDUojIZjN2jDsDDl6HaFwPfredeDf3c8gWxrgGOzNhM5ImG8zJa229K3atc3XxNuHZ4bZCqscDHYr5OT6pd1OcntyfdJM62o9L4MYaZhxdi81lJyB5AqlErwppBdVuhN0kA0ny2J0OblqYW4/XpHQWO8rmY8//YTXwvy1YR//yN05GBHma+7P1fy+MwqrEdt9p3AHQAnazFIQAV+I64f7hTxW4Rgs79NowbGRWKLecPgex3HqFgZBhA63B9FcdfArk1i4zNdvDHVUqM+Z/mbxc30YUTnxA4S07ap9U2WnGxf876Qc63408CDrgT+FLySfwk0NmdYXkEYC11XqG+mMFyE6a6us2mPzlg/Hp/1+jQYTzXRM5RPKftxkWWKawqBC8mA0HXI3+NgaiyTt4LM=
