apiVersion: v1
kind: ConfigMap
metadata:
  name: front-public-configmap
  namespace: ticketing
data:
  NEXT_PUBLIC_ENV: development-microk8s
  NEXT_PUBLIC_API_URL: https://ticketing-api.10.64.140.43.nip.io