apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tickets-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgB7Wgb0SDmogFwR3jkzjvfJyA6GKtz+v6xuBMvyInLkXvszYgRzu+WmZuj5hyvYlxE5/ldYB/i6n+6LB4+iLSFu+8MQ+Vly0dwnJZ+fGmD8W2Rfz390ok6vXJ0wmQP1vuGXzOWCKQj3hK3FP4Hq0yGpBJD1q4IoHllMeo+K5kLKorTDLorWEno8dEgmLUahGT7gciJNrcLK7yRf1e/nW7t9DXnhr0C115Ep5ILYFjJivPhCr01IGHbpEEd2UcKURy4xIGgbXCRFDu2v44CgRwLR5vGSpT6vGfGB3bKNJfGdoknYxLv+BoZqTrqcbvcNUU+YI9CSfmvSch9dTiHm5Tovzt4Bh0vfvPBECMOyFcE5YIuwk0KiJGO9/lI2+kqk6ilvdxEQzt1bYUcPO564VirQ+D/enthzByOk1VbEREUivhkC3RPwBIGYB4hKQK0gITaHatDh1wZ1+fQMpVn2A8rZ4tYn7nL0w4316ZfJjQsAZLMGYOwzq1ZRS7k2Vto8NwDuMei8nnWiDQBAukVj+wYGhlz+TKbiZmiNxl6GSRXlfTyP0mKfc7nPfVOoBJbWc3QHXLc/ySW0X2puxHPtPzb+noB3nlnslCR/DsO1qpcRWdVmwTFOY7mm79ygXuIdSD4Vko15felJ2ceVqL0U8hgH3/dcV9Wcg/tw9M1t1LHOwBA+kI3K5FhBcTjJD6Pc3C3bypRNzQa8eT12bFz1eAVyN8S+Fk/sOUKjoRQgReMHKAJUxCcR8IYWB6kryZB7fcb4cDBX0S8g
