apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: orders-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgCpc2wQlHesBDLAJlJn+wEbccerjFUyEhlXEYrdQNYN4WoWQQ7ar8dFwEuZnCm8qCkWqmx3uu/XeEdwNmh9QbHt2T+FXf36W7GavQdjesdjrQ4o2QMhZ3XHEorUIxvMQqlqUDQklNZHOxJhpl1rs75z5Pm3Y+bV2ZkJJePvt2nkCrQZsXSkMQIeN9Y6b7/I0lEptOspaZY8QVEvo3WBrEy0mleXdtCF6jlAc8WpOu2yNyzb2yWhBx9//rvuVfwT8kUfwuVBSlcNhuBexbk5ts58r+rqsGcm7UruJxpMwYdZxKz1Btvy/zg1MJDIMzLui8zBZqwkVa/9gwm7qT3qUTukBcJX/ZzNAK9NOMV3d+QlF47Kc9Dt3VSNqllvQMAgdgAPTvce7XpB42s92bdhrsSyozBOx60VblzXJied5IhdKPZGdXlY0UMA/RQRuwohb6kawUcnzyXRw99Vgicl8PaTavSQTF/py1uW//50z/f0w0u/gOW1RPSVseXq37kaQTtthOwHagyd4NiuVQV9IR5rJ7HbULZwwDMsq3JZudcXLR6M/P8mq8cbzl7Tm9LYlDo2hp5grgRLIIipxgOsvCS/NHTrucKkX5V+J6s13DoaigVJWC6VkIn9TcAUWWSQVvsFPDGaZQhBRHmBj5v8CEnAEyDMhbkKnjoWPlF9+fOBaxh9TrRvsv027Lx0maOldnA9hZmw7zuD8rBu5XJKJpub02+xYsl8ax1LTCyUhTLp41YeLH+Jgq7hl+1aTFOsANGN+F/5cQ==
