# development overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# override these resources
patchesStrategicMerge:
- 100-auth-configmap.yaml
- 101-auth-secret.yaml
- 102-common-secret.yaml
- 200-auth-deployment.yaml
- 201-auth-mongodb-deployment.yaml
- 900-ticketing-ingress.yaml
# patch 900-ticketing-ingress.yaml resource with the hosts.yaml file
patches:
- path: hosts.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ticketing-ingress
    namespace: ticketing
    version: v1
# path to our base resources
resources:
- ../../base
# set development images and tags
images:
- name: rodarte/msnr-ta-auth-skaffold
  newName: rodarte/msnr-ta-auth-skaffold
  newTag: f3f0cef