# ArgoCD for continuous deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticketing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AlejandroRodarte/course-microservices-ticketing-app.git # our git repo link
    targetRevision: HEAD # target latest commit
    path: infra/k8s/overlays/prod # use production kustomize overlay (ArgoCD supports kustomize)
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc # ArgoCD server is located inside the same cluster where the application lives
    namespace: ticketing # locate it through the application namespace
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
