version: '3.4'

# base version of compose files
services:
  auth:
    image: rodarte/msnr-ta-auth-prod:7537359 # use latest image built by CI/CD pipeline (prod stage)
    ports:
      - '3000:3000' # publish port 3000 of container to port 3000 of virtual computer
    environment:
      - NODE_ENV=production-docker
      - MONGODB_URL_FILE_PATH=/run/secrets/auth_mongodb_url
      - JWT_SECRET_FILE_PATH=/run/secrets/jwt_secret
      - CORS_ORIGIN=http://localhost:3001
      - COOKIE_SESSION_DOMAIN=localhost
    secrets:
      - auth_mongodb_url
      - jwt_secret
    depends_on:
      - auth-mongodb
  auth-mongodb:
    image: mongo:5.0
  front:
    image: rodarte/msnr-ta-front-prod:7537359
    ports:
      - '3001:3001'
    environment:
      - NEXT_PUBLIC_ENV=production-docker
      - NEXT_PUBLIC_API_URL=http://localhost
      - AUTH_MICROSERVICE_NAME=auth
      - NEXT_PUBLIC_AUTH_MICROSERVICE_PORT=3000
secrets:
  auth_mongodb_url:
    file: ./secrets/docker/auth/mongodb-url.txt
  jwt_secret:
    file: ./secrets/docker/common/jwt-secret.txt
