# development override
version: '3.4'

services:
  auth:
    image: rodarte/msnr-ta-auth-dev:0.0.2 # use latest image built by CI/CD pipeline (dev stage)
    volumes:
      - ./auth:/node/app # dev stage sets WORKDIR on /node/app to bindmount local source code there
      - /node/app/node_modules # bind /node/app/node_modules to an empty volume (node_modules will be grabbed on parent folder: /node/node_modules)
    environment:
      - NODE_ENV=development-docker
  auth-mongodb:
    image: mongo:latest
