version: '3.4'

x-common-env-variables: &common-env-variables
  NODE_ENV: production-docker
  JWT_SECRET_FILE_PATH: /run/secrets/jwt_secret
  CORS_ORIGIN: http://localhost:3001
  COOKIE_SESSION_DOMAIN: localhost

x-common-env-nats-variables: &common-env-nats-variables
  NATS_CLUSTER_ID: ticketing
  NATS_SERVER_URL: http://nats:4222

# base version of compose files
services:
  auth:
    image: rodarte/msnr-ta-auth-prod:ab44013 # use latest image built by CI/CD pipeline (prod stage)
    ports:
      - '3000:3000' # publish port 3000 of container to port 3000 of virtual computer
    environment:
      <<: *common-env-variables
      MONGODB_URL_FILE_PATH: /run/secrets/auth_mongodb_url
    secrets:
      - auth_mongodb_url
      - jwt_secret
    depends_on:
      - auth-mongodb
  auth-mongodb:
    image: mongo:5.0
  tickets:
    image: rodarte/msnr-ta-tickets-prod:ab44013
    ports:
      - '3002:3002'
    environment:
      <<: *common-env-variables
      <<: *common-env-nats-variables
      NATS_CLIENT_ID: tickets
      MONGODB_URL_FILE_PATH: /run/secrets/tickets_mongodb_url
    secrets:
      - tickets_mongodb_url
      - jwt_secret
    depends_on:
      - tickets-mongodb
  tickets-mongodb:
    image: mongo:5.0
  front:
    image: rodarte/msnr-ta-front-prod:b89cc02
    ports:
      - '3001:3001'
    environment:
      NEXT_PUBLIC_ENV: production-docker
      NEXT_PUBLIC_API_URL: http://localhost
      AUTH_MICROSERVICE_NAME: auth
      NEXT_PUBLIC_AUTH_MICROSERVICE_PORT: 3000
      TICKETS_MICROSERVICE_NAME: tickets
      NEXT_PUBLIC_TICKETS_MICROSERVICE_PORT: 3002
  nats:
    image: nats-streaming:0.24.5
    command:
      - '-p'
      - '4222'
      - '-m'
      - '8222'
      - '-hbi'
      - '5s'
      - '-hbt'
      - '5s'
      - '-hbf'
      - '2'
      - '-SD'
      - '-cid'
      - 'ticketing'
secrets:
  auth_mongodb_url:
    file: ./secrets/docker/auth/mongodb-url.txt
  tickets_mongodb_url:
    file: ./secrets/docker/tickets/mongodb-url.txt
  jwt_secret:
    file: ./secrets/docker/common/jwt-secret.txt
