# development override
version: '3.4'

services:
  auth:
    image: rodarte/msnr-ta-auth-dev:f8ce26e # use latest image built by CI/CD pipeline (dev stage)
    volumes:
      - ./auth:/node/app # dev stage sets WORKDIR on /node/app to bindmount local source code there
      - /node/app/node_modules # bind /node/app/node_modules to an empty volume (node_modules will be grabbed on parent folder: /node/node_modules)
    environment:
      - NODE_ENV=development-docker
  auth-mongodb:
    image: mongo:latest
  tickets:
    image: rodarte/msnr-ta-tickets-dev:b2f68c6
    volumes:
      - ./tickets:/node/app
      - /node/app/node_modules
    environment:
      - NODE_ENV=development-docker
  tickets-mongodb:
    image: mongo:latest
  front:
    image: rodarte/msnr-ta-front-dev:b89cc02
    volumes:
      - ./client:/node/app
      - /node/app/node_modules
    environment:
      - NEXT_PUBLIC_ENV=development-docker
