# development override
version: '3.4'

x-common-env-variables: &common-env-variables
  NODE_ENV: development-docker

services:
  auth:
    image: rodarte/msnr-ta-auth-dev:34f1d42 # use latest image built by CI/CD pipeline (dev stage)
    volumes:
      - ./auth:/node/app # dev stage sets WORKDIR on /node/app to bindmount local source code there
      - /node/app/node_modules # bind /node/app/node_modules to an empty volume (node_modules will be grabbed on parent folder: /node/node_modules)
    environment:
      <<: *common-env-variables
  auth-mongodb:
    image: mongo:latest
  tickets:
    image: rodarte/msnr-ta-tickets-dev:073368d
    volumes:
      - ./tickets:/node/app
      - /node/app/node_modules
    environment:
      <<: *common-env-variables
  tickets-mongodb:
    image: mongo:latest
  orders:
    image: rodarte/msnr-ta-orders-dev:073368d
    volumes:
      - ./orders:/node/app
      - /node/app/node_modules
    environment:
      <<: *common-env-variables
  orders-mongodb:
    image: mongo:latest
  expiration:
    image: rodarte/msnr-ta-expiration-dev:2fe6e9e
    volumes:
      - ./expiration:/node/app
      - /node/app/node_modules
    environment:
      <<: *common-env-variables
  expiration-redis:
    image: redis:latest
  payments:
    image: rodarte/msnr-ta-payments-dev:073368d
    volumes:
      - ./payments:/node/app
      - /node/app/node_modules
    environment:
      <<: *common-env-variables
  payments-mongodb:
    image: mongo:latest
  front:
    image: rodarte/msnr-ta-front-dev:073368d
    volumes:
      - ./client:/node/app
      - /node/app/node_modules
    environment:
      NEXT_PUBLIC_ENV: development-docker
