version: '3.4'

# base version of compose files
services:
  auth:
    image: rodarte/msnr-ta-auth-prod:0.0.2 # use latest image built by CI/CD pipeline (prod stage)
    ports:
      - '3000:3000' # publish port 3000 of container to port 3000 of virtual computer
    environment:
      - NODE_ENV=production-docker
      - MONGODB_URL_FILE_PATH=/run/secrets/auth_mongodb_url
      - JWT_SECRET_FILE_PATH=/run/secrets/jwt_secret
    secrets:
      - auth_mongodb_url
      - jwt_secret
    depends_on:
      - auth-mongodb
  auth-mongodb:
    image: mongo:5.0
secrets:
  auth_mongodb_url:
    file: ./secrets/docker/auth/mongodb-url.txt
  jwt_secret:
    file: ./secrets/docker/common/jwt-secret.txt
