# development override
version: '3.4'

x-common-env-variables: &common-env-variables
  NODE_ENV: development-docker

services:
  auth:
    image: rodarte/msnr-ta-auth-dev:ab44013 # use latest image built by CI/CD pipeline (dev stage)
    volumes:
      - ./auth:/node/app # dev stage sets WORKDIR on /node/app to bindmount local source code there
      - /node/app/node_modules # bind /node/app/node_modules to an empty volume (node_modules will be grabbed on parent folder: /node/node_modules)
    environment:
      <<: *common-env-variables
  auth-mongodb:
    image: mongo:latest
  tickets:
    image: rodarte/msnr-ta-tickets-dev:ab44013
    volumes:
      - ./tickets:/node/app
      - /node/app/node_modules
    environment:
      <<: *common-env-variables
  tickets-mongodb:
    image: mongo:latest
  orders:
    image: rodarte/msnr-ta-orders-dev:04398b2
    volumes:
      - ./orders:/node/app
      - /node/app/node_modules
    environment:
      <<: *common-env-variables
  orders-mongodb:
    image: mongo:latest
  front:
    image: rodarte/msnr-ta-front-dev:04398b2
    volumes:
      - ./client:/node/app
      - /node/app/node_modules
    environment:
      NEXT_PUBLIC_ENV: development-docker
