version: '3.4'

x-common-env-variables: &common-env-variables
  NODE_ENV: production-docker
  JWT_SECRET_FILE_PATH: /run/secrets/jwt_secret
  CORS_ORIGIN: http://localhost:3001
  COOKIE_SESSION_DOMAIN: localhost

x-common-env-nats-variables: &common-env-nats-variables
  NATS_CLUSTER_ID: ticketing
  NATS_SERVER_URL: http://nats:4222

# base version of compose files
services:
  auth:
    image: rodarte/msnr-ta-auth-prod:cf7fc04 # use latest image built by CI/CD pipeline (prod stage)
    ports:
      - '3000:3000' # publish port 3000 of container to port 3000 of virtual computer
    environment:
      <<: *common-env-variables
      MONGODB_URL_FILE_PATH: /run/secrets/auth_mongodb_url
    secrets:
      - auth_mongodb_url
      - jwt_secret
    depends_on:
      - auth-mongodb
  auth-mongodb:
    image: mongo:5.0
  tickets:
    image: rodarte/msnr-ta-tickets-prod:577e925
    ports:
      - '3002:3002'
    environment:
      <<: *common-env-variables
      <<: *common-env-nats-variables
      NATS_CLIENT_ID: tickets
      MONGODB_URL_FILE_PATH: /run/secrets/tickets_mongodb_url
    secrets:
      - tickets_mongodb_url
      - jwt_secret
    depends_on:
      - tickets-mongodb
  tickets-mongodb:
    image: mongo:5.0
  orders:
    image: rodarte/msnr-ta-orders-prod:cf7fc04
    ports:
      - '3003:3003'
    environment:
      <<: *common-env-variables
      <<: *common-env-nats-variables
      NATS_CLIENT_ID: orders
      MONGODB_URL_FILE_PATH: /run/secrets/orders_mongodb_url
      EXPIRATION_WINDOW_SECONDS: 30
    secrets:
      - orders_mongodb_url
      - jwt_secret
    depends_on:
      - orders-mongodb
  orders-mongodb:
    image: mongo:5.0
  expiration:
    image: rodarte/msnr-ta-expiration-prod:2fe6e9e
    environment:
      <<: *common-env-variables
      <<: *common-env-nats-variables
      NATS_CLIENT_ID: expiration
      REDIS_HOST_FILE_PATH: /run/secrets/redis_host
    secrets:
      - redis_host
    depends_on:
      - expiration-redis
  expiration-redis:
    image: redis:7.0
  payments:
    image: rodarte/msnr-ta-payments-prod:cf7fc04
    ports:
      - '3004:3004'
    environment:
      <<: *common-env-variables
      <<: *common-env-nats-variables
      NATS_CLIENT_ID: payments
      MONGODB_URL_FILE_PATH: /run/secrets/payments_mongodb_url
      STRIPE_API_KEY_FILE_PATH: /run/secrets/stripe_api_key
    secrets:
      - payments_mongodb_url
      - jwt_secret
      - stripe_api_key
    depends_on:
      - payments-mongodb
  payments-mongodb:
    image: mongo:5.0
  front:
    image: rodarte/msnr-ta-front-prod:2be88cf
    ports:
      - '3001:3001'
    environment:
      NEXT_PUBLIC_ENV: production-docker
      NEXT_PUBLIC_API_URL: http://localhost
      AUTH_MICROSERVICE_NAME: auth
      NEXT_PUBLIC_AUTH_MICROSERVICE_PORT: 3000
      TICKETS_MICROSERVICE_NAME: tickets
      NEXT_PUBLIC_TICKETS_MICROSERVICE_PORT: 3002
      ORDERS_MICROSERVICE_NAME: orders
      NEXT_PUBLIC_ORDERS_MICROSERVICE_PORT: 3003
      PAYMENTS_MICROSERVICE_NAME: payments
      NEXT_PUBLIC_PAYMENTS_MICROSERVICE_PORT: 3004
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_test_51L3nTtIWPfnfPOmq5I97aU1tPKrTiPgdP3DJipBNIJwLRbc4HP8QlGBkL3Fg4GF35YnyNXIYu5giGJuReR5gyysu00nBVr8fYj
  nats:
    image: nats-streaming:0.24.5
    command:
      - '-p'
      - '4222'
      - '-m'
      - '8222'
      - '-hbi'
      - '5s'
      - '-hbt'
      - '5s'
      - '-hbf'
      - '2'
      - '-SD'
      - '-cid'
      - 'ticketing'
secrets:
  auth_mongodb_url:
    file: ./secrets/docker/auth/mongodb-url.txt
  tickets_mongodb_url:
    file: ./secrets/docker/tickets/mongodb-url.txt
  orders_mongodb_url:
    file: ./secrets/docker/orders/mongodb-url.txt
  payments_mongodb_url:
    file: ./secrets/docker/payments/mongodb-url.txt
  redis_host:
    file: ./secrets/docker/expiration/redis-host.txt
  jwt_secret:
    file: ./secrets/docker/common/jwt-secret.txt
  stripe_api_key:
    file: ./secrets/docker/payments/stripe-api-key.txt
