apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kustomize:
    paths:
      - ./infra/k8s/base
      - ./infra/k8s/overlays/dev
build:
  local:
    push: false
  artifacts:
    - image: rodarte/msnr-ta-auth-skaffold
      context: auth
      docker:
        dockerfile: Dockerfile
        target: skaffold
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .