apiVersion: skaffold/v2beta28
kind: Config
profiles:
  - name: dev-microk8s # profile name (why we run "skaffold dev")
    build:
      insecureRegistries: ['localhost:32000']
      artifacts:
        - image: localhost:32000/msnr-ta-auth-skaffold
          context: auth # build image based on what is inside ./auth
          sync:
            manual:
              - src: src/***/*.ts # recompile when a .ts file inside ./auth/src changes
                dest: .
          docker:
            dockerfile: Dockerfile
            target: skaffold # build image based on skaffold-specific image
        - image: localhost:32000/msnr-ta-front-skaffold
          context: client
          sync:
            manual:
              - src: src/***/*.ts
                dest: .
              - src: src/***/*.tsx
                dest: .
              - src: src/***/*.css
                dest: .
          docker:
            dockerfile: Dockerfile
            target: skaffold
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - ./infra/k8s/overlays/dev-microk8s # kustomize deployment method; use development overlay
  - name: dev-gcloud # profile name (why we run "skaffold dev")
    build:
      artifacts:
        - image: us.gcr.io/prime-byway-274602/msnr-ta-auth-skaffold
          context: auth # build image based on what is inside ./auth
          sync:
            manual:
              - src: src/**/*.ts # recompile when a .ts file inside ./auth/src changes
                dest: .
          docker:
            dockerfile: Dockerfile
            target: skaffold # build image based on skaffold-specific image
        - image: us.gcr.io/prime-byway-274602/msnr-ta-front-skaffold
          context: client
          sync:
            manual:
              - src: src/**/*.ts
                dest: .
              - src: src/**/*.tsx
                dest: .
              - src: src/**/*.css
                dest: .
          docker:
            dockerfile: Dockerfile
            target: skaffold # build image based on skaffold-specific image
      googleCloudBuild:
        projectId: prime-byway-274602
    deploy:
      kustomize:
        paths:
          - ./infra/k8s/overlays/dev-gcloud # kustomize deployment method; use development overlay
