apiVersion: skaffold/v2beta12
kind: Config
profiles:
  - name: dev
    build:
      artifacts:
        - image: rodarte/msnr-ta-auth-skaffold
          context: auth
          sync:
            manual:
            - src: src/**/*.ts
              dest: .
          docker:
            dockerfile: Dockerfile
            target: skaffold
      local:
        push: false
    deploy:
      kustomize:
        paths:
        - ./infra/k8s/overlays/dev