apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: ticketing
spec:
  template:
    data: null
    metadata:
      name: auth-secret
      namespace: ticketing
