apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: common-secret
  namespace: ticketing
spec:
  template:
    data: null
    metadata:
      name: common-secret
      namespace: ticketing
