apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      namespace: ticketing
    spec:
      containers:
        - name: auth
          image: rodarte/ms-node-react-ticketing-app-auth:prod
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: PORT