apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
      namespace: ticketing
    spec:
      volumes:
        - name: env
          configMap:
            name: front-public-configmap
            items:
              - key: .env
                path: .env
      containers:
        - name: next
          image: rodarte/msnr-ta-front-prod
          volumeMounts:
            - name: env
              mountPath: /node/.env
              readOnly: true
              subPath: .env
          env:
            - name: AUTH_MICROSERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: front-private-configmap
                  key: AUTH_MICROSERVICE_NAME
            - name: AUTH_MICROSERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: front-private-configmap
                  key: AUTH_MICROSERVICE_PORT
            - name: TICKETS_MICROSERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: front-private-configmap
                  key: TICKETS_MICROSERVICE_NAME
            - name: TICKETS_MICROSERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: front-private-configmap
                  key: TICKETS_MICROSERVICE_PORT
            - name: ORDERS_MICROSERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: front-private-configmap
                  key: ORDERS_MICROSERVICE_NAME
            - name: ORDERS_MICROSERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: front-private-configmap
                  key: ORDERS_MICROSERVICE_PORT
            - name: PAYMENTS_MICROSERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: front-private-configmap
                  key: PAYMENTS_MICROSERVICE_NAME
            - name: PAYMENTS_MICROSERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: front-private-configmap
                  key: PAYMENTS_MICROSERVICE_PORT
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health/healthz
              port: 3001
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 20
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health/healthz
              port: 3001
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 20
