apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
      namespace: ticketing
    spec:
      containers:
        - name: tickets
          image: rodarte/msnr-ta-tickets-prod
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: NODE_ENV
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: CORS_ORIGIN
            - name: COOKIE_SESSION_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: COOKIE_SESSION_DOMAIN
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: NATS_CLUSTER_ID
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: NATS_SERVER_URL
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: tickets-secret
                  key: MONGODB_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: JWT_SECRET
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /tickets/health/healthz
              port: 3002
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /tickets/health/healthz
              port: 3002
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
