apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
      namespace: ticketing
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.24.5
          # -p, --port: use port for clients
          # -m, --http_port: use port for http monitoring
          # -hbi, --hb_interval: interval at which server sends heartbeat to client
          # -hbt, --hb_timeout: how long server waits for a heartbeat response from client
          # -hbf, --hb_fail_count: number of failed heartbeats before server closes client connection
          # -SD, --stan-debug: enable STAN debugging tool
          # -cid, --clister_id: cluster ID
          args:
            [
              '-p',
              '4222',
              '-m',
              '8222',
              '-hbi',
              '5s',
              '-hbt',
              '5s',
              '-hbf',
              '2',
              '-SD',
              '-cid',
              'ticketing',
            ]
