apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
      namespace: ticketing
    spec:
      containers:
        - name: orders
          image: rodarte/msnr-ta-orders-prod
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: NODE_ENV
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: CORS_ORIGIN
            - name: COOKIE_SESSION_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: COOKIE_SESSION_DOMAIN
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: NATS_CLUSTER_ID
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: NATS_SERVER_URL
            - name: EXPIRATION_WINDOW_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: orders-configmap
                  key: EXPIRATION_WINDOW_SECONDS
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: MONGODB_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: JWT_SECRET
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /orders/health/healthz
              port: 3003
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /orders/health/healthz
              port: 3003
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
