apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
      namespace: ticketing
    spec:
      containers:
        - name: expiration
          image: rodarte/msnr-ta-expiration-prod
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: NODE_ENV
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: NATS_CLUSTER_ID
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: NATS_SERVER_URL
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: expiration-secret
                  key: REDIS_HOST
          readinessProbe:
            failureThreshold: 3
            exec:
              command:
                - node
                - /node/src/healthcheck.js
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 45
          livenessProbe:
            failureThreshold: 3
            exec:
              command:
                - node
                - /node/src/healthcheck.js
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 45
