apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ticketing
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      port: 3000
      protocol: TCP
      targetPort: 3000