apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: ticketing
spec:
  type: ClusterIP
  selector:
    app: front
  ports:
    - name: front
      port: 3001
      protocol: TCP
      targetPort: 3001
