apiVersion: v1
kind: Service
metadata:
  name: tickets-mongodb-service
  namespace: ticketing
spec:
  type: ClusterIP
  selector:
    app: tickets-mongodb
  ports:
    - name: db
      port: 27017
      protocol: TCP
      targetPort: 27017
