apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: ticketing
spec:
  type: ClusterIP
  selector:
    app: nats
  ports:
    # we set -p 4222 as an argument in the nats container at the nats-deployment resource
    - name: client
      port: 4222
      protocol: TCP
      targetPort: 4222
    # we set -m 8222 as an argument in the nats container at the nats-deployment resource
    - name: monitoring
      port: 8222
      protocol: TCP
      targetPort: 8222
