apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: ticketing
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: orders
      port: 3003
      protocol: TCP
      targetPort: 3003
