apiVersion: v1
kind: Service
metadata:
  name: expiration-redis-service
  namespace: ticketing
spec:
  type: ClusterIP
  selector:
    app: expiration-redis
  ports:
    - name: db
      port: 6379
      protocol: TCP
      targetPort: 6379
