apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: ticketing
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - name: payments
      port: 3004
      protocol: TCP
      targetPort: 3004
