# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticketing-ingress
  namespace: ticketing # application namespace
spec:
  ingressClassName: public
  rules:
    - host: ticketing-api.dummy-value.com # dummy host value (replaces by kustomize)
      http:
        paths:
          - path: /auth # http://ticketing-api.dummy-value.com/auth redirects traffic to our auth-service Service resource, located on port 3000 within the cluster
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 3000
