# Ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ticketing-ingress
  namespace: ticketing # application namespace
  annotations:
    kubernetes.io/ingress.class: nginx # use NGINX as our reverse proxy
spec:
  rules:
    - host: ticketing-api.dummy-value.com # dummy host value (replaces by kustomize)
      http:
        paths:
          - path: /auth # http://ticketing-api.dummy-value.com/auth redirects traffic to our auth-service Service resource, located on port 3000 within the cluster
            backend:
              serviceName: auth-service
              servicePort: 3000