# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticketing-ingress
  namespace: ticketing # application namespace
spec:
  rules:
    - host: ticketing-api.dummy-value.com # dummy host value (replaces by kustomize)
      http:
        paths:
          - path: /auth # http://ticketing-api.dummy-value.com/auth redirects traffic to our auth-service Service resource, located on port 3000 within the cluster
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 3000
          - path: /tickets # http://ticketing-api.dummy-value.com/tickets redirects traffic to our tickets-service Service resource, located on port 3002 within the cluster
            pathType: Prefix
            backend:
              service:
                name: tickets-service
                port:
                  number: 3002
    - host: ticketing.dummy-value.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-service
                port:
                  number: 3001
