apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgAJ2+zWSBqS99Cr4bn0rgYDWXcsi2/a2sPuDReR8pfiVoJjJR4ztEeJzbjlroar03VupmdtOHkMbtLSikiBZdBz98175UnII8E5H9YpxtuTCHowfKOVlaKN1rHBY+Mdkhm8RI1y1hLV3UKqgPpcXgVIQ3wFh/2ad/vyC3+UPtel6gPBfc0yPwA3GlYUzvgMs2Fa21y7uNMjVRsKUkbGo2rrET2RjRFzV0p5SWsOhSAMFaxjdpNXy/5+ZFNVOtGFEmJM/SUyT3S1appOlGZ9oSSecjItXxT2PIp7PF6qSlZ0if2UE4YzXxtoBeS6fKPWhqCkTpTsNU5nAr5VqhOpPYy2QOckUkc5JFuMRjKMcNwWIXNEQWVDzUaQ0jUpVEqffOf8YxxaA+EG79+s2GlCwu4Wixen7Carhv6gue1nSUNtSuRDMboQwzKNyPeCfRKeI41B5u5p0YPN6nitOYH42/phqdE3DJTqQGDljfQtZnFTerjTDcL3b9Nn7g47s+a1CgxDYS4fW9ZDpuTDn5fq8JbdEG9+srsNoy8yNqQyNP8b+w7VNHS5UEc0Of+++7Ik5O6iBTStqKL8P6xCtVP8H+OVEkxwNsimpWkpDbJGPP74oud7thlIDuTAqNjRjKMIeB2D8AlaRyayXV9j6hPklF/49QSaAEiyGM66XgTNO0W6VKl6iUGdyqI8WTMIMbh374vwkEpBt950PmhC/JtdSGUzg9voGb/hHZ76LrnK+6VI7kKk74AJdDTgxqJ9K6C8xR75
