apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: common-secret
  namespace: ticketing
spec:
  encryptedData:
    JWT_SECRET: AgBdywmWfITw33/VEOTycU5iVAi94KhQZWwSkN+Mx5ZKsOCSSdelzCcnexUXryzld62PRUfL5yWZ8zRisnkwkQjegbfa+2VUb7tAmddFMkhwBzUXz6nc9EHNic4Orv497VGO9DopngggH8LoIGrvDfZOP6aHFs1ZUcuTOvHm0Vi8GsXvaeCNB619oqDEfDch6Y14QhS46+r1yrW3Jsh3gjjx3TEbBVvmzx3q4o0nfP46y3U8psdSAme2zwr5tpuhb9/Ph0zZy2Djfhs+n5PpIsty7H1qGUo+zhHY/TIln7QKibJTNe/ERBORYKxGugZ/DlyQnopFTeSTODJDaoPzZfvv6MEFZ00CTzGex1OyT+PzMD9q8kSMEhk3mJ6PN6qqYT2CTdabEq8GG7COZG5W1N6LSLGDFx9WZBQ2EIW73WRh7vOc6OMW/nWVTgUuHVA3h2LRzj3LLv5ZXcYRm6EHU8DoXzd6HQzODu6DUtAOsgCaEO5pJFuGYJZ7cJGhYQI/pDeup7BDVH7bP63rD3D9DVHmCso8HD/4t0VKR+pKA1UhlBL6WUOBHlmEYyjJUO5cDso9jObnt2aSIGB21+eJFiuWRQHx0ba/R6MgOF2pjMl7W2x9yUAMRe2Iv6mzFmXLeRB5zCkX7O883GxFT1KbliFmAKJwEnsaNxpXYuBy4LKlW0GEYPtlgUFPSmGtxCtAKm2dMtbGu5LFEnrbS5YZ3S/w2lhetwZmCmsaOJR+R84=
