apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tickets-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgAtA9kX/I9/mrBIaEnuS66JtMDfz0D/elCylIBAQwVQBDh5lL8qcp+3UCZkhwQtJQyWddheRd9JWfLgQ26w/+rTG5XZUzIujowD3JDoIl62YBKmkW7hqw4sGU8XyR9t1GFJwV68Udr2SP0nI/8ACmAZZnUW7moHAO1YIhHHo+i2X3kLTJ81drLNJMEuxlcys2BcXie+VReGDylI0SNR7XdIklmauwqetAnlTVMol+MzV1d5Cq/HxJt9P+o6RxuiK5Zf3/ZFeXZ8j/4GAF7c6vzC+bgU7Qx7lqTi50DdS68FmXWEkG2NepUmz2VuNBDIQEQq17hfPuiqUXZ39x8olc/d28XhLFmw2h91yzRra8aYRunf8oH9ZneDVwLQOBamFR7e8IiJIToltuD7OLWxN0iEvsgqBxuqyUTAvkVMRG2YWdNcTqP7Hz6PBU1aF1Iy5Ew5W5V1YcLv6cQN1fau7pT1upw67N/BblcXRMjSDVl3IT9wkZPR0a+/XiTsoSfu3TS6upp7XzEUGGWgirmCqPKfO5ph4izUN5ZJT+ZaqDWeOPWLwukvBJ5++YMuIs+Q06Gw24kA0VdDJUQWAI5o6YtcmCeCgkzsyxHSgui1T8tj4MC98yZHQ4HDeVVybtV4yA5Y+6aPS/JW4I+gecKmcwfTbs+rE+dvRmpxmSp4vP0rcl3QisxecqltUxilBQisbDQBEYpUIqKe/JKGCBbWOlQuTjjOWqEyv4UIVTRkxZxz9VkAsSaowtUgPXVE8T3r3WfPNdAcLZei
