apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: orders-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgB0x6QIiHGbp9NAGXQg47P9v7nrMVgan18ljY7TOUJNvvmTkYAgINJekL/SLT1pYP0kMviqrARQxlt7fafzZCuO59AkoC1NUPpErIbHlhX5NrS6x+YWgcFXJGB2kpXxH73s+zHQOFG8gMJ/8+ifK3M+wTzPhAi42Uyoz249zgCf34U+e5GzSNAH/xw1LoSIOlr6hQmmLiVztRG/Jv1nzHbeL8ubLIdBmbENtPnUdUpcpFqO6EVbuj8RplTzfpheNhVUyeUPv/RTKJTs3lEveH+0v5NmCe071pF6ti6LfPVPMpO2G1EWr0g1JetWFZaruEkMlJKjli3GN2YvYOlKUD9Xe4KLQZPNgGO0IeovPtVLqu4ClybiNGQLjJ0uwCuh0iGj3HYX5QMSwwYUaoFftsjhy38Sfi71CKl0SQgirIGmST3kjGYAEcWnzRRC/oDMiJF1diPPKFoLBkdP3101c+iKiRsSzuT+43hFOhuYKpL13wcttYXO9S3Rlc4td6usB39hW+9+IjNUPk4hiRp8LIirsWpmk6orF7HsXqr/d4F6FKinEbvGm4DQBTfDuxaCz/eS1uJXZao2jeCNqCNQE5BsQ4POzkjxJhyq0B96UEzhAACnWZmXfVRrjKbPAR1guyAedFGF6Qz6i8Uhp08M0yrq66X5x+L6Fc8CV+lxUptEmwRK15pFiDEOdSQQFejBKMD7iRS8JrcTEcujPzaFA0ZimOIPLUaN9KmQjHnjDThASm5yei0VBZpwqbP2uzj1Xz7+qQ1mSQ==
