apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  namespace: ticketing
spec:
  template:
    spec:
      containers:
        - name: orders
          image: us.gcr.io/prime-byway-274602/msnr-ta-orders-skaffold
          env:
            - name: FORCE_INSECURE_COOKIE
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: FORCE_INSECURE_COOKIE
          startupProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 15
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 20
