apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongodb-deployment
  namespace: ticketing
spec:
  template:
    spec:
      containers:
        - name: orders-mongodb
          image: mongo:latest
