apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: ticketing
spec:
  template:
    spec:
      containers:
        - name: auth
          image: rodarte/ms-node-react-ticketing-app-auth:dev