apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: ticketing
spec:
  template:
    spec:
      containers:
        - name: auth
          image: rodarte/msnr-ta-auth-skaffold
          startupProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 45