apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: ticketing
spec:
  template:
    spec:
      containers:
        - name: auth
          image: rodarte/msnr-ta-auth-skaffold:0.0.1