apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgBllDorhi9eHP3jcLVpRycMaIh4YpeVwfER0mzlKIwWBRbvzzC9oxHXeNLK1ZwKP6jqZy2ibn2oqo4JfT0JJSy7kORtMfAF6e4tOVLVQ4z/kwpawneehrcFPwj/TkFgzgH86Bfmz2KX3/7giR1a0oK4oKphC+fgM9eANrb0DOhykh0ZjLo3o7kPs8VhrVQDA8NBqdId3nqccjBktTyyaydRoGyZvQiDa0F35J9dPcME0Bo0bm8MrUGEYNs3CC9b+0oifU6t9TRiAW9uqhpRA7x5wVp0+5/zXFK1CZ1xbQ16xAofPKHmN4/UtEdmSGowrKg8UVY5ElYPaOtE/RumUaYF/Q3RFtm9HvGeF23EvRF/KWgQHWeLQqRQXXR2OP6m8V6qceK+neYmt/JktWOAJAFzTNZvSGbeNfTGmDyFR+PlexRbIP3YamEOgS53q75pNARovKFZ+sT09vMXJvdtkxDnmbZpeiMhNw8qRxNIaytPYZ8p53ZCHKyZkg32ufVWRz+NgQjqjijYadP/55YnQRLcMRo38yNxBcDWYfiJu3x8IC0eQIBN8FY7WMgS3dmFSx2P/H6JH8jiTgoxl1MBURCkCa+dtd2sQwT+i0f36xAduPmVeIvGlApLJhiaiOdIlZcnO7/aYpA87hhi2cExAca3RsgspkojojlK/NZxNcc1RX0iTk5TxFbIXGqiYYjb9dHMY8NjNboVjBMX8h3nUaB3uNQa5sT3a2aLZSPJIjZ2HKDBoU2qOdlZSXW1UXQUvSMZ
