apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgApHTmSwsPRpYwRG34wnXonRlyBA3xH/DTkiySy72pZY9l+o+cqCSU28Rgo2a1AhNAEr2lihaPsZZu8v7eYM5SI2xkSvAnNklkuqwloUTSls1euIRe5fD9IFBMkyQyCkuS8zQ1e/lRp+fsM/gZ7/qTznY/PELPf/luMaPDIg4PAXD9zccu9hQYjRB6TAC6fq/flNVBAqmolJWn1LZApWoBxC6nc91iPp6ia9/5pwYWsgbSf/++maaznyYcRWIgRYCZ2A9JiWnvdwy7zYXC7y3yu0fet/As72enb6Jkq99brDQrGEpXFXgelrc6tQFATeFDbj9g5g22YaWz5LK5ys4lWAR2ABypxDN+e6T+a7Kf+lcHxSdPTjYQWflzv/+ru1+igWiGg6IDsysewZgbwszJ8f5s/ohY6vpmjItHiXbhjy7zsx3Qh256IexyUV0lpNAK7nf2btsrI+ep37LPBjZDoAvoDlGu8zi3cmRsb+khL49T8J6a9EpmxQRY1imqOUgeJQ8HlfJByCmTcF42bodnorDehiZfuecy5hl6Lx64YnLG/HpxzSLRitseUxCtJIuvwRCIa2WeXLPsvIOXS7+O9v6VBafqivrCOyqR82P9i1khcVUTJDW2F++mQlj5VSVijLOHiXn8gC+njBC+ZUFINNxm3gyKfNR5AuxU6SB2AHMmQclPfnPlM5hnuvwtConU4fnpLN0a30Dg3Ywwab3TSvFkyWJSH0mA+apuuEqF13GnGGG31R1MAb+c9cK2oRSFl
