apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tickets-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgCeIZff7cznpnS5fnsBr903nbSY22TkVF8pdkebvdCxLnKFFRXWPjq0VuPRlQZBf1Y3h3RytHsq1f7qfzdI+DaibOE78QMqyLrpkbU7/+XP14T11MxkTJgmLzX/FOCpUX+UX2IoXcum1C2aKZElgD2wSdo+s6nv+Cip73jOAO6zrhsUOwXACq4c0oiQFroGA7TCr4Io+qbiwhp4ZFySswA8kozxuOUtf15AN8+FleS5bsqDW6D0Emk0LVONNzCjKHIgPItsCoEF4oJt21xg4sjmF0yZAqEjsxOxRMY9sBURbHKw3LL9Mv4WHVn0wSKgA9T4ota/lmNFh35stWl2iqP1g70hpOMzMWGQgY7ygZlOKeSCT6omBvvAQXXLAQMYFgBnYvstn2+KGvsPfJIzXofVT0fI1qL75rKTKJ5hZa14OCiphrJT1UgVKfjzJ+td98aBmS//y7PdcHrdKSSXQw4rNxUuJEb2E+ifl8tTOljUOtqGJlRbQwvxjl5rifP2zsm/T+bNRCyrNU4UqBKyny19FC2H49zGpb4+VoJYagGB1U++B9h01SzIYvRqdu7vk2zzHV25GPSOGxnwczIGiNFfP9QOpInlcAySvga+akWszHBsMgRvECix/rn1wWTN9PaI31vH3BCzCV8LRJKJYD+gZ4zxp9346/XpDFmcHi6GuqgYZ4vPaLe4YXBRBDb/DAgI02uEb2R9fB149J1OguzqCFQpTDv4JTd8a0RStonRZL/KZtdgYLSG8wvvfCB9fHXU/s8qe/Hz
