apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tickets-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgCX8K8sWTcUar/IGX0K90UlxfIPk2Uj6aM8P6ZLwQF8oDihkNL1/0BUG5cx/aIGEa0FoafQilDFAwQwPbMyhiNhypNXVubvUyt/qNLR/M0QIdrAfn53+OB5NZf1i79k/fW79A5AAF5Z9CwzzOSVcj3eSHmWVhQjfwOwkkqjpSQ2XVA9TyvURDh2efy3UqNlsqbhqGxblAITGMYA2ANv+8mB2+b0VwdN9m226gEoR1zI2wP/AjHbAZUmzZ66+PT635fWHny5of9+BFE11QkhvzmHc2ecfELr1lwEBEAEIT4GW7CjUV52r2wlVr8FK+ciKEcKYKHO/FqJH6Z59WPzq03ZjP7xaDoUWWZUi1MADFJ3luXr0u/wUd3riZzg8555HnKZekCJhmDRDYiefPimRnxUR9mimlhRsotl/JbrkyxdhVih5JoHldbcWuKuNqK3w3HksF6NBW32MF4G4zwvyqkZuzPqpo9I2PPE2UsKjZeBz6hgT7/cNiKYKV1v8rZbRaLNfI3EwxlQ1TUllcvACnlQL5GB2TR3eJN+/DXngdV0E2iYa730y5/NjVWG2XPaY3/QcipwRuM8lIdfWYjLBjxwkNW6Rchw3Rik5dgFf2yaIdUoefnyumqGgeR/ZXPXrx+1fdb7KnV+d7299xHDuF+mvJIKyfAV7GO5CC2eZvFiki0IVkjdvxfkQ/V4cqz0gFv1GvhgxAXY6w/yPFQ9ebCSi4F7QE3gSHlXidXloPtFgi8VCp5bp1WWsmTItMqB1iYu5X3piEFK
