apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: orders-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgBetZt55k+4FlqxC5hiYksmoHXfVPsV1+VgJ3zKTjxZO4oSzufEe6kPFdR+Ml0XhpuO9gd0anNCdls07IYe49RCFHb4EK+36A2rbWXR5pFvnSy/mTGGPXL8dEyHiAqTyf35hajl57W0KHiy9OVeSVtVa93hv2XEdapIqZ1DQcxryC5vsgsmaOuoyGxGQwwOSN8WPuRRTE5h+m3oWgbi3B7b0u1ofWGhlH4L73iAPmr0eIvSuSpz9duF7VZKKxmjqGxwG3pmRd867n73B9zW5xPwuq0JJs9I6xSzVg9kIikO4RZJIHtw+hD7s2ymzz4SV10ymI3IK33vxgiNnnI5cAIl7xndcarpavcT2yFCkbZKFmb4mDeHjsOQDRcuuEQnF9Z8XHOqgmH5vEK2886NRslJUonnK/SnJNACII74xRLFjJnNoXeu4dlEDc9rZyyktpi01hOmO5fcRsmTkRzHu/ZRY0AST3WlW19q4kU9wyiXRb/8y6TOzRIQ7exhVIxh7d6Ykljl0+8+uGLJEuyW2pIMwdBImSodwyrq9BBkoEQv9cH2B4o2QqUDLNY9hAkTam2ceogYCmYDTCrHPqehC3L3uH0DTe6AXygv57IR/ccbK7WEF74PXjcjL7P9WH71yws0DWbb8TCbT8V1WvzkASaA05EOVQ4Za6cI9Dt7vD03pWoYiAcHFVFxcdroXPLNFFo2bHF78mSQWoCZE8pX7EXi1QoNEerMQNY1AtMdxlEFoSZeLPxkBAo4a1/xzWGI9SE1TKsZ9A==
