apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: orders-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgDWCsGERTFRYW4dPPzuzP/iy5XP8dS3tIGxiX2DBh1AU/ZN0Lu1EmrkRaYwqJVXhnpaEnuANa5RtHDly/mQhmnl+NldN2N4GLK4V2NAvtaBLFqD1CziIVVfiDhR1jNfR73Zf6DBtqvQzP2q59TYzKfr0IOCcOAd5VxFk0ro8DOmN0odVYLwCxHy9oo/XHnNlkWRoPz2+DEUUrBkpNSsEA/cNayuVSgv06VsfEQ3Sd2bnn71uS+J5hN6wXZ0O2yeV/0ZZItITAvBmOrOdz46obVAb680PTu7N+avPXJKz3ECFVQBLnpv4RZBX57dT+7nbqHVYgviI8atyH9/BT2Wb/C49qz1I5RMYaOLqnTwt1QCMOzLoJAOzJAcIxFmDFR01iBYteWF7/g9NCP1W2I9O8KpNwjNfaJwz2+4RYEhmGHH93MNKp2xtXohoRolMTjfMsGRj7s/tZjZ3wJp8i04ouxqpxExsHoqACerKsxqAhZu6vfoxTYQkBozmt4B2Ra7bekz70JuNL2yHr/p+KyqGWffx+vA7g2cLNnI7R3CFGoqCzmzngcaclsvChuLduZlD/1bhI3phFMSQotlj7r8lyIhCLUH6oBcmUGFojVI28qYofjrfVb91cAI3GJCn4cTgbFAUwf+2ZaZnYMBn4bPB0GandmVk/WV+9xMwTw4uAEIgJ6E4/SKIY0aUPxxphfRSkw0Ld9H9x7TNk9ELdy1QhGRbD4rkI9xKkaDy/vipyYkTbc3TP/iePrBpOwg9Xt/lDJI5/oyLQ==
