apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: expiration-secret
  namespace: ticketing
spec:
  encryptedData:
    REDIS_HOST: AgAmnkzgTHovouhnjW056eeLVrBqDFcCsYGotSnYSBOIhjceJfe2u3hnXgKjTJm/mIiqsNKXbRGeg4BBASIlpQSndNB4LkothFyG4cnrBCUT0wDD6gtPFFRuh3UERJIiFLAkloyvchyYBhWXE2foC9zi23PcMq/11TCsRikAfQL9w5QQadzxmpU3x8Zlc3AcT4QGe2fcomxGnt3FJ8eA7ayRJn8lTICuJmGrNQ2gOkqk0pnnQi8kgztuRsasFEVGwufmllGV+pVoln6cwakzwbsH15BKImQOO9p9k/G/RgaUA/89RnwDeV5RtAUQ/FqVgUUYHsibvdKy7jHkNnmB/1/L5zKbom3lFAB8TsP+0fOmYWpjZTTpoJmLj7If7kld5NEbRU7vI8pwGmLyVzvwfBlfMi8H1p1yO3XsqRVpWf4VlTJhEpfsmKTCupHEmXE7vNsEeOBHgq9r+4D+9iR1+njL1gbeiFo9XyKPALUperxHvcFhiLUOHP3QK5Mi8UY6aipGq5qFaZTMJksaoM0UISyAkTPao/famRYirxyZbH+WL8msQyga0IoGBv96SCGXcarzRUjDAKX3VGpb3r1Prkdo6sIbfbUlDzeHB5cccpLpGtI513wFFgdA5An+NjH3FJYn1+dSZzKgONFdqW9t48jzyuJ6dkAi9CkVftJsFRwFHfMnMzqlsh//+woVwhV8PvSyyxHOwcgXJZF1CUsSF3wU75giaNvAw8k=
