# production overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# override these resources
patchesStrategicMerge:
- 101-auth-secret.yaml
- 102-common-secret.yaml
- 103-front-configmap.yaml
- 104-common-configmap.yaml
- 106-tickets-secret.yaml
- 108-orders-secret.yaml
- 200-auth-deployment.yaml
- 202-front-deployment.yaml
- 203-tickets-deployment.yaml
- 206-orders-deployment.yaml
- 900-ticketing-ingress.yaml
# patch 900-ticketing-ingress.yaml resource with the hosts.yaml file
patchesJson6902:
- path: hosts.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ticketing-ingress
    namespace: ticketing
    version: v1
# path to our base resources
resources:
- ../../base
# set production images and tags (edited by GitHub Actions for CD)
images:
- name: rodarte/msnr-ta-auth-prod
  newName: rodarte/msnr-ta-auth-prod
  newTag: ab44013
- name: rodarte/msnr-ta-front-prod
  newName: rodarte/msnr-ta-front-prod
  newTag: b89cc02
- name: rodarte/msnr-ta-tickets-prod
  newName: rodarte/msnr-ta-tickets-prod
  newTag: ab44013
- name: rodarte/msnr-ta-orders-prod
  newName: rodarte/msnr-ta-orders-prod
  newTag: ab44013
