apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesJson6902:
  - path: hosts.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: ticketing-ingress
      namespace: ticketing
      version: v1beta1
bases:
  - ../../base