# production overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# override these resources
patchesStrategicMerge:
- 200-auth-deployment.yaml
- 900-ticketing-ingress.yaml
# patch 900-ticketing-ingress.yaml resource with the hosts.yaml file
patchesJson6902:
- path: hosts.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ticketing-ingress
    namespace: ticketing
    version: v1
# path to our base resources
resources:
- ../../base
# set production images and tags (edited by GitHub Actions for CD)
images:
- name: rodarte/msnr-ta-auth-prod
  newName: rodarte/msnr-ta-auth-prod
  newTag: cac2bc2
