apiVersion: v1
kind: Namespace
metadata:
  name: ticketing
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: ticketing
---
apiVersion: v1
data:
  COOKIE_SESSION_DOMAIN: .104.197.128.80.nip.io
  CORS_ORIGIN: https://ticketing.104.197.128.80.nip.io
  FORCE_INSECURE_COOKIE: "true"
  NATS_CLUSTER_ID: ticketing
  NATS_SERVER_URL: http://nats-service:4222
  NODE_ENV: development-gcloud
kind: ConfigMap
metadata:
  name: common-configmap
  namespace: ticketing
---
apiVersion: v1
data:
  AUTH_MICROSERVICE_NAME: auth-service
  AUTH_MICROSERVICE_PORT: "3000"
  NEXT_PUBLIC_API_URL: https://ticketing-api.104.197.128.80.nip.io
  NEXT_PUBLIC_ENV: development-gcloud
  TICKETS_MICROSERVICE_NAME: tickets-service
  TICKETS_MICROSERVICE_PORT: "3002"
kind: ConfigMap
metadata:
  name: front-configmap
  namespace: ticketing
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-configmap
  namespace: ticketing
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tickets-configmap
  namespace: ticketing
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongodb-service
  namespace: ticketing
spec:
  ports:
  - name: db
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: auth-mongodb
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ticketing
spec:
  ports:
  - name: auth
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: auth
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: ticketing
spec:
  ports:
  - name: front
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: front
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: ticketing
spec:
  ports:
  - name: client
    port: 4222
    protocol: TCP
    targetPort: 4222
  - name: monitoring
    port: 8222
    protocol: TCP
    targetPort: 8222
  selector:
    app: nats
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongodb-service
  namespace: ticketing
spec:
  ports:
  - name: db
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: orders-mongodb
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: ticketing
spec:
  ports:
  - name: orders
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: orders
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongodb-service
  namespace: ticketing
spec:
  ports:
  - name: db
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: tickets-mongodb
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-service
  namespace: ticketing
spec:
  ports:
  - name: tickets
    port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: tickets
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      namespace: ticketing
    spec:
      containers:
      - env:
        - name: FORCE_INSECURE_COOKIE
          valueFrom:
            configMapKeyRef:
              key: FORCE_INSECURE_COOKIE
              name: common-configmap
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: common-configmap
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              key: CORS_ORIGIN
              name: common-configmap
        - name: COOKIE_SESSION_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: COOKIE_SESSION_DOMAIN
              name: common-configmap
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              key: MONGODB_URL
              name: auth-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: common-secret
        image: us.gcr.io/prime-byway-274602/msnr-ta-auth-skaffold
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /auth/health/healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: auth
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /auth/health/healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        startupProbe:
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongodb-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongodb
  template:
    metadata:
      labels:
        app: auth-mongodb
      namespace: ticketing
    spec:
      containers:
      - image: mongo:latest
        name: auth-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
      namespace: ticketing
    spec:
      containers:
      - env:
        - name: NEXT_PUBLIC_ENV
          valueFrom:
            configMapKeyRef:
              key: NEXT_PUBLIC_ENV
              name: front-configmap
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              key: NEXT_PUBLIC_API_URL
              name: front-configmap
        - name: AUTH_MICROSERVICE_NAME
          valueFrom:
            configMapKeyRef:
              key: AUTH_MICROSERVICE_NAME
              name: front-configmap
        - name: AUTH_MICROSERVICE_PORT
          valueFrom:
            configMapKeyRef:
              key: AUTH_MICROSERVICE_PORT
              name: front-configmap
        image: us.gcr.io/prime-byway-274602/msnr-ta-front-skaffold
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/health/healthz
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 25
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 20
        name: next
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/health/healthz
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 20
        startupProbe:
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 3001
          timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
      namespace: ticketing
    spec:
      containers:
      - args:
        - -p
        - "4222"
        - -m
        - "8222"
        - -hbi
        - 5s
        - -hbt
        - 5s
        - -hbf
        - "2"
        - -SD
        - -cid
        - ticketing
        image: nats-streaming:0.24.5
        name: nats
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
      namespace: ticketing
    spec:
      containers:
      - env:
        - name: FORCE_INSECURE_COOKIE
          valueFrom:
            configMapKeyRef:
              key: FORCE_INSECURE_COOKIE
              name: common-configmap
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: common-configmap
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              key: CORS_ORIGIN
              name: common-configmap
        - name: COOKIE_SESSION_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: COOKIE_SESSION_DOMAIN
              name: common-configmap
        - name: NATS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: NATS_CLUSTER_ID
              name: common-configmap
        - name: NATS_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NATS_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: NATS_SERVER_URL
              name: common-configmap
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              key: MONGODB_URL
              name: orders-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: common-secret
        image: us.gcr.io/prime-byway-274602/msnr-ta-orders-skaffold
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /orders/health/healthz
            port: 3003
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: orders
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /orders/health/healthz
            port: 3003
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        startupProbe:
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3003
          timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongodb-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongodb
  template:
    metadata:
      labels:
        app: orders-mongodb
      namespace: ticketing
    spec:
      containers:
      - image: mongo:latest
        name: orders-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
      namespace: ticketing
    spec:
      containers:
      - env:
        - name: FORCE_INSECURE_COOKIE
          valueFrom:
            configMapKeyRef:
              key: FORCE_INSECURE_COOKIE
              name: common-configmap
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: common-configmap
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              key: CORS_ORIGIN
              name: common-configmap
        - name: COOKIE_SESSION_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: COOKIE_SESSION_DOMAIN
              name: common-configmap
        - name: NATS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: NATS_CLUSTER_ID
              name: common-configmap
        - name: NATS_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NATS_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: NATS_SERVER_URL
              name: common-configmap
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              key: MONGODB_URL
              name: tickets-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: common-secret
        image: us.gcr.io/prime-byway-274602/msnr-ta-tickets-skaffold
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /tickets/health/healthz
            port: 3002
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: tickets
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /tickets/health/healthz
            port: 3002
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        startupProbe:
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3002
          timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongodb-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongodb
  template:
    metadata:
      labels:
        app: tickets-mongodb
      namespace: ticketing
    spec:
      containers:
      - image: mongo:latest
        name: tickets-mongodb
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgAJ2+zWSBqS99Cr4bn0rgYDWXcsi2/a2sPuDReR8pfiVoJjJR4ztEeJzbjlroar03VupmdtOHkMbtLSikiBZdBz98175UnII8E5H9YpxtuTCHowfKOVlaKN1rHBY+Mdkhm8RI1y1hLV3UKqgPpcXgVIQ3wFh/2ad/vyC3+UPtel6gPBfc0yPwA3GlYUzvgMs2Fa21y7uNMjVRsKUkbGo2rrET2RjRFzV0p5SWsOhSAMFaxjdpNXy/5+ZFNVOtGFEmJM/SUyT3S1appOlGZ9oSSecjItXxT2PIp7PF6qSlZ0if2UE4YzXxtoBeS6fKPWhqCkTpTsNU5nAr5VqhOpPYy2QOckUkc5JFuMRjKMcNwWIXNEQWVDzUaQ0jUpVEqffOf8YxxaA+EG79+s2GlCwu4Wixen7Carhv6gue1nSUNtSuRDMboQwzKNyPeCfRKeI41B5u5p0YPN6nitOYH42/phqdE3DJTqQGDljfQtZnFTerjTDcL3b9Nn7g47s+a1CgxDYS4fW9ZDpuTDn5fq8JbdEG9+srsNoy8yNqQyNP8b+w7VNHS5UEc0Of+++7Ik5O6iBTStqKL8P6xCtVP8H+OVEkxwNsimpWkpDbJGPP74oud7thlIDuTAqNjRjKMIeB2D8AlaRyayXV9j6hPklF/49QSaAEiyGM66XgTNO0W6VKl6iUGdyqI8WTMIMbh374vwkEpBt950PmhC/JtdSGUzg9voGb/hHZ76LrnK+6VI7kKk74AJdDTgxqJ9K6C8xR75
  template:
    metadata:
      name: auth-secret
      namespace: ticketing
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: common-secret
  namespace: ticketing
spec:
  encryptedData:
    JWT_SECRET: AgBdywmWfITw33/VEOTycU5iVAi94KhQZWwSkN+Mx5ZKsOCSSdelzCcnexUXryzld62PRUfL5yWZ8zRisnkwkQjegbfa+2VUb7tAmddFMkhwBzUXz6nc9EHNic4Orv497VGO9DopngggH8LoIGrvDfZOP6aHFs1ZUcuTOvHm0Vi8GsXvaeCNB619oqDEfDch6Y14QhS46+r1yrW3Jsh3gjjx3TEbBVvmzx3q4o0nfP46y3U8psdSAme2zwr5tpuhb9/Ph0zZy2Djfhs+n5PpIsty7H1qGUo+zhHY/TIln7QKibJTNe/ERBORYKxGugZ/DlyQnopFTeSTODJDaoPzZfvv6MEFZ00CTzGex1OyT+PzMD9q8kSMEhk3mJ6PN6qqYT2CTdabEq8GG7COZG5W1N6LSLGDFx9WZBQ2EIW73WRh7vOc6OMW/nWVTgUuHVA3h2LRzj3LLv5ZXcYRm6EHU8DoXzd6HQzODu6DUtAOsgCaEO5pJFuGYJZ7cJGhYQI/pDeup7BDVH7bP63rD3D9DVHmCso8HD/4t0VKR+pKA1UhlBL6WUOBHlmEYyjJUO5cDso9jObnt2aSIGB21+eJFiuWRQHx0ba/R6MgOF2pjMl7W2x9yUAMRe2Iv6mzFmXLeRB5zCkX7O883GxFT1KbliFmAKJwEnsaNxpXYuBy4LKlW0GEYPtlgUFPSmGtxCtAKm2dMtbGu5LFEnrbS5YZ3S/w2lhetwZmCmsaOJR+R84=
  template:
    metadata:
      name: common-secret
      namespace: ticketing
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: orders-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgB0x6QIiHGbp9NAGXQg47P9v7nrMVgan18ljY7TOUJNvvmTkYAgINJekL/SLT1pYP0kMviqrARQxlt7fafzZCuO59AkoC1NUPpErIbHlhX5NrS6x+YWgcFXJGB2kpXxH73s+zHQOFG8gMJ/8+ifK3M+wTzPhAi42Uyoz249zgCf34U+e5GzSNAH/xw1LoSIOlr6hQmmLiVztRG/Jv1nzHbeL8ubLIdBmbENtPnUdUpcpFqO6EVbuj8RplTzfpheNhVUyeUPv/RTKJTs3lEveH+0v5NmCe071pF6ti6LfPVPMpO2G1EWr0g1JetWFZaruEkMlJKjli3GN2YvYOlKUD9Xe4KLQZPNgGO0IeovPtVLqu4ClybiNGQLjJ0uwCuh0iGj3HYX5QMSwwYUaoFftsjhy38Sfi71CKl0SQgirIGmST3kjGYAEcWnzRRC/oDMiJF1diPPKFoLBkdP3101c+iKiRsSzuT+43hFOhuYKpL13wcttYXO9S3Rlc4td6usB39hW+9+IjNUPk4hiRp8LIirsWpmk6orF7HsXqr/d4F6FKinEbvGm4DQBTfDuxaCz/eS1uJXZao2jeCNqCNQE5BsQ4POzkjxJhyq0B96UEzhAACnWZmXfVRrjKbPAR1guyAedFGF6Qz6i8Uhp08M0yrq66X5x+L6Fc8CV+lxUptEmwRK15pFiDEOdSQQFejBKMD7iRS8JrcTEcujPzaFA0ZimOIPLUaN9KmQjHnjDThASm5yei0VBZpwqbP2uzj1Xz7+qQ1mSQ==
  template:
    metadata:
      name: orders-secret
      namespace: ticketing
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tickets-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgAtA9kX/I9/mrBIaEnuS66JtMDfz0D/elCylIBAQwVQBDh5lL8qcp+3UCZkhwQtJQyWddheRd9JWfLgQ26w/+rTG5XZUzIujowD3JDoIl62YBKmkW7hqw4sGU8XyR9t1GFJwV68Udr2SP0nI/8ACmAZZnUW7moHAO1YIhHHo+i2X3kLTJ81drLNJMEuxlcys2BcXie+VReGDylI0SNR7XdIklmauwqetAnlTVMol+MzV1d5Cq/HxJt9P+o6RxuiK5Zf3/ZFeXZ8j/4GAF7c6vzC+bgU7Qx7lqTi50DdS68FmXWEkG2NepUmz2VuNBDIQEQq17hfPuiqUXZ39x8olc/d28XhLFmw2h91yzRra8aYRunf8oH9ZneDVwLQOBamFR7e8IiJIToltuD7OLWxN0iEvsgqBxuqyUTAvkVMRG2YWdNcTqP7Hz6PBU1aF1Iy5Ew5W5V1YcLv6cQN1fau7pT1upw67N/BblcXRMjSDVl3IT9wkZPR0a+/XiTsoSfu3TS6upp7XzEUGGWgirmCqPKfO5ph4izUN5ZJT+ZaqDWeOPWLwukvBJ5++YMuIs+Q06Gw24kA0VdDJUQWAI5o6YtcmCeCgkzsyxHSgui1T8tj4MC98yZHQ4HDeVVybtV4yA5Y+6aPS/JW4I+gecKmcwfTbs+rE+dvRmpxmSp4vP0rcl3QisxecqltUxilBQisbDQBEYpUIqKe/JKGCBbWOlQuTjjOWqEyv4UIVTRkxZxz9VkAsSaowtUgPXVE8T3r3WfPNdAcLZei
  template:
    metadata:
      name: tickets-secret
      namespace: ticketing
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ticketing-ingress
  namespace: ticketing
spec:
  rules:
  - host: ticketing-api.104.197.128.80.nip.io
    http:
      paths:
      - backend:
          service:
            name: auth-service
            port:
              number: 3000
        path: /auth
        pathType: Prefix
      - backend:
          service:
            name: tickets-service
            port:
              number: 3002
        path: /tickets
        pathType: Prefix
      - backend:
          service:
            name: orders-service
            port:
              number: 3003
        path: /orders
        pathType: Prefix
  - host: ticketing.104.197.128.80.nip.io
    http:
      paths:
      - backend:
          service:
            name: front-service
            port:
              number: 3001
        path: /
        pathType: Prefix
