apiVersion: v1
kind: Namespace
metadata:
  name: ticketing
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: ticketing
---
apiVersion: v1
data:
  COOKIE_SESSION_DOMAIN: .10.64.140.43.nip.io
  CORS_ORIGIN: https://ticketing.10.64.140.43.nip.io
  FORCE_INSECURE_COOKIE: "true"
  NODE_ENV: development-microk8s
kind: ConfigMap
metadata:
  name: common-configmap
  namespace: ticketing
---
apiVersion: v1
data:
  AUTH_MICROSERVICE_NAME: auth-service
  AUTH_MICROSERVICE_PORT: "3000"
  NEXT_PUBLIC_API_URL: https://ticketing-api.10.64.140.43.nip.io
  NEXT_PUBLIC_ENV: development-microk8s
  TICKETS_MICROSERVICE_NAME: tickets-service
  TICKETS_MICROSERVICE_PORT: "3002"
kind: ConfigMap
metadata:
  name: front-configmap
  namespace: ticketing
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tickets-configmap
  namespace: ticketing
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongodb-service
  namespace: ticketing
spec:
  ports:
  - name: db
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: auth-mongodb
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ticketing
spec:
  ports:
  - name: auth
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: auth
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: ticketing
spec:
  ports:
  - name: front
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: front
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongodb-service
  namespace: ticketing
spec:
  ports:
  - name: db
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: tickets-mongodb
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-service
  namespace: ticketing
spec:
  ports:
  - name: tickets
    port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: tickets
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      namespace: ticketing
    spec:
      containers:
      - env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: common-configmap
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              key: CORS_ORIGIN
              name: common-configmap
        - name: COOKIE_SESSION_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: COOKIE_SESSION_DOMAIN
              name: common-configmap
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              key: MONGODB_URL
              name: auth-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: common-secret
        image: localhost:32000/msnr-ta-auth-skaffold
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /auth/health/healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: auth
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /auth/health/healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        startupProbe:
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongodb-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongodb
  template:
    metadata:
      labels:
        app: auth-mongodb
      namespace: ticketing
    spec:
      containers:
      - image: mongo:latest
        name: auth-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
      namespace: ticketing
    spec:
      containers:
      - env:
        - name: NEXT_PUBLIC_ENV
          valueFrom:
            configMapKeyRef:
              key: NEXT_PUBLIC_ENV
              name: front-configmap
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              key: NEXT_PUBLIC_API_URL
              name: front-configmap
        - name: AUTH_MICROSERVICE_NAME
          valueFrom:
            configMapKeyRef:
              key: AUTH_MICROSERVICE_NAME
              name: front-configmap
        - name: AUTH_MICROSERVICE_PORT
          valueFrom:
            configMapKeyRef:
              key: AUTH_MICROSERVICE_PORT
              name: front-configmap
        image: localhost:32000/msnr-ta-front-skaffold
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/health/healthz
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 25
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 20
        name: next
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/health/healthz
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 20
        startupProbe:
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 3001
          timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
      namespace: ticketing
    spec:
      containers:
      - env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: common-configmap
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              key: CORS_ORIGIN
              name: common-configmap
        - name: COOKIE_SESSION_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: COOKIE_SESSION_DOMAIN
              name: common-configmap
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              key: MONGODB_URL
              name: tickets-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: common-secret
        image: localhost:32000/msnr-ta-tickets-skaffold
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /tickets/health/healthz
            port: 3002
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: tickets
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /tickets/health/healthz
            port: 3002
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        startupProbe:
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3002
          timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongodb-deployment
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongodb
  template:
    metadata:
      labels:
        app: tickets-mongodb
      namespace: ticketing
    spec:
      containers:
      - image: mongo:latest
        name: tickets-mongodb
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgCSiC9a1bgq8Ev0i+vYuyUfZ7y6uuXKXmUnN7ezWSKULLfj/BJdz8BuJyvfVJQ6yMQQnW7n6VL0H4Irkxzciy1GK9LeltyZPXliW4stVC5T5NMlwcolrLm7T9m/O39drbQMIxtZuGkak2uvM3cR9KLeV9/L1dgAQYpUz9Ks0gTIAGSLLpvGKtKGyNyv+K5Xtp7yuU4QYpZqlUS2UpCoXDdAs+05tSZDEG65Gqc8YB4aKx+oyON08gamswfB/SG1/REd18+vgTTwoGQiQfDlmBX4zH2Tg8ENhScOEOtpQUDzTuIifHfzioGvfDvUTJeWfKtuF3ob86WExC+D8BAQpoWDCqxlueIy0WgqezM4rAtQHdADYgIQjbkbbdvETF/POtwl8uAJTN4zo3q3KEo3T/NqqjQUFYYq5bdGHzsy0xqMqEsUr1tMHBlO97Tjd+/+NnNXjLbl8/gQnybtLaXN8IvjQUCJN29BS0gSTmlNfi1J3YSYAn5Tur+CEClDzFkliftO2RxeB43rKeOZ8SOUEEeg1ecil8sF7PtI3F8fwzOe4AcKiQgH9/TpOEMwfe1h9d1M1g0Z5xtsIqPYInBfcim+JXt5OK71F+qpOB5WSIksoW5TT+eLYIM8Y0NE/VPori+C9aRvDy/5FVhMsNwhhm/yO5msaMFc26Roi7e4nVSA/Hdi6CsdFmjqICHSUMwUQdR0z/0P64tXEcQb0C5/YcJcitEDSoXe39O8dTQpv9r26bIgFqiE/2INa4RVPfkvpcrW
  template:
    metadata:
      name: auth-secret
      namespace: ticketing
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: common-secret
  namespace: ticketing
spec:
  encryptedData:
    JWT_SECRET: AgChq4iG3mg/GNecWr9NzSoQkoYhv5E+OiM4gYXWqGlYGOefEl28wozXmHrKiBzfLo1O+0tOT2CJiC5L9Ys2kCbgQXxi2bKC7tVD8IOaI+dpV4WUTRr/UW8qT5eQtOdy/ScWFF533z2El+P7gClIaEfgVmOikWR72nSCkidcll5UgGuSJUcdtS8d4jA7wfxCQWrczHSn+u5jLKw+5+3QSXCvA/L5FvD5Ky6sQrLoBTNbtxnyl5GRvWXBVJb/tO/9f5aCII5PIvlEAapGnBGGPY8mzuu9gOWZmWhVs4MVTrAbh73lEpvavkCbqtnIn/DGi1nFilN440FnZqXO+xTd0hbnDUojIZjN2jDsDDl6HaFwPfredeDf3c8gWxrgGOzNhM5ImG8zJa229K3atc3XxNuHZ4bZCqscDHYr5OT6pd1OcntyfdJM62o9L4MYaZhxdi81lJyB5AqlErwppBdVuhN0kA0ny2J0OblqYW4/XpHQWO8rmY8//YTXwvy1YR//yN05GBHma+7P1fy+MwqrEdt9p3AHQAnazFIQAV+I64f7hTxW4Rgs79NowbGRWKLecPgex3HqFgZBhA63B9FcdfArk1i4zNdvDHVUqM+Z/mbxc30YUTnxA4S07ap9U2WnGxf876Qc63408CDrgT+FLySfwk0NmdYXkEYC11XqG+mMFyE6a6us2mPzlg/Hp/1+jQYTzXRM5RPKftxkWWKawqBC8mA0HXI3+NgaiyTt4LM=
  template:
    metadata:
      name: common-secret
      namespace: ticketing
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tickets-secret
  namespace: ticketing
spec:
  encryptedData:
    MONGODB_URL: AgB7Wgb0SDmogFwR3jkzjvfJyA6GKtz+v6xuBMvyInLkXvszYgRzu+WmZuj5hyvYlxE5/ldYB/i6n+6LB4+iLSFu+8MQ+Vly0dwnJZ+fGmD8W2Rfz390ok6vXJ0wmQP1vuGXzOWCKQj3hK3FP4Hq0yGpBJD1q4IoHllMeo+K5kLKorTDLorWEno8dEgmLUahGT7gciJNrcLK7yRf1e/nW7t9DXnhr0C115Ep5ILYFjJivPhCr01IGHbpEEd2UcKURy4xIGgbXCRFDu2v44CgRwLR5vGSpT6vGfGB3bKNJfGdoknYxLv+BoZqTrqcbvcNUU+YI9CSfmvSch9dTiHm5Tovzt4Bh0vfvPBECMOyFcE5YIuwk0KiJGO9/lI2+kqk6ilvdxEQzt1bYUcPO564VirQ+D/enthzByOk1VbEREUivhkC3RPwBIGYB4hKQK0gITaHatDh1wZ1+fQMpVn2A8rZ4tYn7nL0w4316ZfJjQsAZLMGYOwzq1ZRS7k2Vto8NwDuMei8nnWiDQBAukVj+wYGhlz+TKbiZmiNxl6GSRXlfTyP0mKfc7nPfVOoBJbWc3QHXLc/ySW0X2puxHPtPzb+noB3nlnslCR/DsO1qpcRWdVmwTFOY7mm79ygXuIdSD4Vko15felJ2ceVqL0U8hgH3/dcV9Wcg/tw9M1t1LHOwBA+kI3K5FhBcTjJD6Pc3C3bypRNzQa8eT12bFz1eAVyN8S+Fk/sOUKjoRQgReMHKAJUxCcR8IYWB6kryZB7fcb4cDBX0S8g
  template:
    metadata:
      name: tickets-secret
      namespace: ticketing
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticketing-ingress
  namespace: ticketing
spec:
  ingressClassName: public
  rules:
  - host: ticketing-api.10.64.140.43.nip.io
    http:
      paths:
      - backend:
          service:
            name: auth-service
            port:
              number: 3000
        path: /auth
        pathType: Prefix
      - backend:
          service:
            name: tickets-service
            port:
              number: 3002
        path: /tickets
        pathType: Prefix
  - host: ticketing.10.64.140.43.nip.io
    http:
      paths:
      - backend:
          service:
            name: front-service
            port:
              number: 3001
        path: /
        pathType: Prefix
